# Generated by Django 2.2.7 on 2025-12-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_auto_20220930_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='platform',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('payoneer', 'Payoneer'), ('upwork', 'Upwork'), ('freelancer', 'Freelancer'), ('toptal', 'Toptal'), ('binance', 'Binance'), ('metamask', 'MetaMask'), ('tron', 'TronLink'), ('trustwallet', 'Trustwallet'), ('bank', 'Bank'), ('bitwage', 'Bitwage'), ('copperx', 'Copperx'), ('card', 'Card')], max_length=10),
        ),
    ]
