# Generated by Django 2.2.7 on 2025-12-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_auto_20251224_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
