# Generated by Django 2.2.7 on 2025-12-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_partner_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='archived',
            field=models.BooleanField(default=False, help_text='Indicates whether the payment account is actively used or archived due to suspension', verbose_name='Achived'),
        ),
    ]
