# Generated by Django 2.2.7 on 2026-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_paymentaccount_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
