# Generated by Django 2.2.7 on 2022-09-29 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220124_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'role': 1}, related_name='admin_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
